### ISSUE TITLE
请问复制链接以后怎么在社区服检视啊

### ISSUE THREAD

**Issue by skyzhou95** [qianjiachun/csgo-skin-compare#1]

**Comment by qianjiachun** [comment]
比如onet4p社区的buff检视服务器，你直接在聊天框粘贴发送就可以了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月31日(周一) 下午3:07
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qianjiachun/csgo-skin-compare] 请问复制链接以后怎么在社区服检视啊 (Issue #1)




 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
